packages:
  - 'packages/*'
overrides:
  nanoid: '3.3.11'
  uuid: '9.0.1'
allowBuilds:
  '@apollo/protobufjs': true
  '@nestjs/core': true
  '@parcel/watcher': true
  '@swc/core': true
  bcrypt: true
  bufferutil: true
  esbuild: true
  sharp: true
  simple-git-hooks: true
  utf-8-validate: true
